name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o "Iskandarani_Android_Project.zip1.zip" -d project
          find project -name gradlew -type f -exec chmod +x {} \;

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build APK
        run: |         
       GRADLEW=$(find project -name gradlew -type f | head -1)
          chmod +x "$GRADLEW"
          cd "$(dirname "$GRADLEW")"
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: project/**/build/outputs/apk/**/*.apk
